import { MasteringPreset, GenreType } from '../types';

export const GENRE_PRESETS: Record<GenreType, MasteringPreset> = {
  hiphop: {
    id: 'hiphop-modern',
    name: 'Hip Hop & Trap Heavyweight',
    genre: 'hiphop',
    description: 'Deep controlled sub-bass, 808 transient punch, scooped mud, and ultra-crisp hi-hat sparkle with brickwall loudness.',
    cleanup: {
      enabled: true,
      deHum: true,
      highPassFreq: 28,
      deHarsh: true,
      deHarshAmount: 35,
      lowPassFreq: 20000,
    },
    bass: {
      enabled: true,
      subBoostDb: 5.5,
      subFreq: 50,
      punchDb: 3.2,
      subHarmonics: 40,
      monoBelowFreq: 110,
    },
    clarity: {
      enabled: true,
      airDb: 4.8,
      presenceDb: 2.2,
      vocalShine: 55,
    },
    sonicHd: {
      enabled: true,
      mode: 'solid-state',
      drive: 45,
      warmth: 30,
      analogGlue: 55,
    },
    spatial: {
      enabled: true,
      stereoWidth: 125,
      mode: 'mid-side',
      surroundSpread: 35,
    },
    loudness: {
      ceilingDb: -1.0,
      inputGainDb: 3.5,
      limiterRelease: 65,
    },
  },
  edm: {
    id: 'edm-festival',
    name: 'EDM & Club Banger',
    genre: 'edm',
    description: 'Pumping sidechain punch, massive supersaw width, tight sub-mono fold, and maximum club impact.',
    cleanup: {
      enabled: true,
      deHum: true,
      highPassFreq: 30,
      deHarsh: true,
      deHarshAmount: 40,
      lowPassFreq: 21000,
    },
    bass: {
      enabled: true,
      subBoostDb: 6.0,
      subFreq: 45,
      punchDb: 4.5,
      subHarmonics: 50,
      monoBelowFreq: 130,
    },
    clarity: {
      enabled: true,
      airDb: 6.0,
      presenceDb: 3.5,
      vocalShine: 60,
    },
    sonicHd: {
      enabled: true,
      mode: 'console',
      drive: 50,
      warmth: 35,
      analogGlue: 65,
    },
    spatial: {
      enabled: true,
      stereoWidth: 145,
      mode: 'synthetic-room',
      surroundSpread: 65,
    },
    loudness: {
      ceilingDb: -0.3,
      inputGainDb: 5.5,
      limiterRelease: 45,
    },
  },
  pop: {
    id: 'pop-radio',
    name: 'Modern Pop & Chart Radio',
    genre: 'pop',
    description: 'Vocal-forward presence, polished radio sheen, balanced sub-bass, and crystal-clear stereo imaging.',
    cleanup: {
      enabled: true,
      deHum: true,
      highPassFreq: 25,
      deHarsh: true,
      deHarshAmount: 45,
      lowPassFreq: 20500,
    },
    bass: {
      enabled: true,
      subBoostDb: 3.5,
      subFreq: 60,
      punchDb: 2.8,
      subHarmonics: 25,
      monoBelowFreq: 100,
    },
    clarity: {
      enabled: true,
      airDb: 5.2,
      presenceDb: 3.8,
      vocalShine: 70,
    },
    sonicHd: {
      enabled: true,
      mode: 'tape',
      drive: 30,
      warmth: 40,
      analogGlue: 50,
    },
    spatial: {
      enabled: true,
      stereoWidth: 120,
      mode: 'synthetic-room',
      surroundSpread: 45,
    },
    loudness: {
      ceilingDb: -1.0,
      inputGainDb: 2.5,
      limiterRelease: 80,
    },
  },
  rock: {
    id: 'rock-wall',
    name: 'Rock, Indie & Metal Wall of Sound',
    genre: 'rock',
    description: 'Aggressive midrange guitar bite, warm bass guitar low-end glue, dynamic drum room snap, and analog tape drive.',
    cleanup: {
      enabled: true,
      deHum: true,
      highPassFreq: 32,
      deHarsh: true,
      deHarshAmount: 30,
      lowPassFreq: 19500,
    },
    bass: {
      enabled: true,
      subBoostDb: 2.8,
      subFreq: 65,
      punchDb: 4.0,
      subHarmonics: 20,
      monoBelowFreq: 90,
    },
    clarity: {
      enabled: true,
      airDb: 3.5,
      presenceDb: 4.5,
      vocalShine: 40,
    },
    sonicHd: {
      enabled: true,
      mode: 'tube',
      drive: 60,
      warmth: 55,
      analogGlue: 60,
    },
    spatial: {
      enabled: true,
      stereoWidth: 115,
      mode: 'mid-side',
      surroundSpread: 30,
    },
    loudness: {
      ceilingDb: -1.0,
      inputGainDb: 3.0,
      limiterRelease: 90,
    },
  },
  rnb: {
    id: 'rnb-velvet',
    name: 'R&B, Soul & Neo-Soul Velvet',
    genre: 'rnb',
    description: 'Warm luxurious low-end, silky vocal heights, rich analog harmonics, and intimate dimensional space.',
    cleanup: {
      enabled: true,
      deHum: true,
      highPassFreq: 24,
      deHarsh: true,
      deHarshAmount: 50,
      lowPassFreq: 20000,
    },
    bass: {
      enabled: true,
      subBoostDb: 4.8,
      subFreq: 55,
      punchDb: 2.5,
      subHarmonics: 35,
      monoBelowFreq: 105,
    },
    clarity: {
      enabled: true,
      airDb: 4.0,
      presenceDb: 2.5,
      vocalShine: 65,
    },
    sonicHd: {
      enabled: true,
      mode: 'tape',
      drive: 35,
      warmth: 65,
      analogGlue: 45,
    },
    spatial: {
      enabled: true,
      stereoWidth: 125,
      mode: 'synthetic-room',
      surroundSpread: 50,
    },
    loudness: {
      ceilingDb: -1.0,
      inputGainDb: 2.0,
      limiterRelease: 100,
    },
  },
  acoustic: {
    id: 'acoustic-pure',
    name: 'Acoustic, Folk & Singer-Songwriter',
    genre: 'acoustic',
    description: 'Natural organic transparency, preserved dynamic range, woody instrument body, and pristine top-end air.',
    cleanup: {
      enabled: true,
      deHum: true,
      highPassFreq: 35,
      deHarsh: true,
      deHarshAmount: 25,
      lowPassFreq: 21000,
    },
    bass: {
      enabled: true,
      subBoostDb: 1.5,
      subFreq: 75,
      punchDb: 1.8,
      subHarmonics: 10,
      monoBelowFreq: 80,
    },
    clarity: {
      enabled: true,
      airDb: 3.2,
      presenceDb: 2.0,
      vocalShine: 50,
    },
    sonicHd: {
      enabled: true,
      mode: 'tube',
      drive: 20,
      warmth: 40,
      analogGlue: 30,
    },
    spatial: {
      enabled: true,
      stereoWidth: 110,
      mode: 'synthetic-room',
      surroundSpread: 30,
    },
    loudness: {
      ceilingDb: -1.0,
      inputGainDb: 1.2,
      limiterRelease: 120,
    },
  },
  jazz: {
    id: 'jazz-audiophile',
    name: 'Jazz & Classical Audiophile Master',
    genre: 'jazz',
    description: 'True hi-fi audiophile transparency, micro-dynamics preserved, rich acoustic realism, and expansive concert hall depth.',
    cleanup: {
      enabled: true,
      deHum: true,
      highPassFreq: 20,
      deHarsh: false,
      deHarshAmount: 15,
      lowPassFreq: 22000,
    },
    bass: {
      enabled: false,
      subBoostDb: 0.8,
      subFreq: 60,
      punchDb: 1.0,
      subHarmonics: 5,
      monoBelowFreq: 0,
    },
    clarity: {
      enabled: true,
      airDb: 2.0,
      presenceDb: 1.2,
      vocalShine: 30,
    },
    sonicHd: {
      enabled: true,
      mode: 'console',
      drive: 15,
      warmth: 30,
      analogGlue: 20,
    },
    spatial: {
      enabled: true,
      stereoWidth: 115,
      mode: 'synthetic-room',
      surroundSpread: 40,
    },
    loudness: {
      ceilingDb: -1.0,
      inputGainDb: 0.5,
      limiterRelease: 150,
    },
  },
  cinematic: {
    id: 'cinematic-atmos',
    name: 'Cinematic & Ambient Immersive 3D',
    genre: 'cinematic',
    description: 'Wide mid/side imaging, synthetic room texture, deep sub-bass, and high-frequency lift.',
    cleanup: {
      enabled: true,
      deHum: true,
      highPassFreq: 20,
      deHarsh: false,
      deHarshAmount: 20,
      lowPassFreq: 22000,
    },
    bass: {
      enabled: true,
      subBoostDb: 4.0,
      subFreq: 40,
      punchDb: 2.5,
      subHarmonics: 45,
      monoBelowFreq: 70,
    },
    clarity: {
      enabled: true,
      airDb: 5.5,
      presenceDb: 2.8,
      vocalShine: 45,
    },
    sonicHd: {
      enabled: true,
      mode: 'tape',
      drive: 30,
      warmth: 50,
      analogGlue: 40,
    },
    spatial: {
      enabled: true,
      stereoWidth: 160,
      mode: 'synthetic-room',
      surroundSpread: 80,
    },
    loudness: {
      ceilingDb: -1.0,
      inputGainDb: 2.0,
      limiterRelease: 110,
    },
  },
  podcast: {
    id: 'podcast-vocal',
    name: 'Podcast, Voiceover & Spoken Word',
    genre: 'podcast',
    description: 'Speech-focused filtering, sibilance reduction, proximity-bass correction, and conservative output control.',
    cleanup: {
      enabled: true,
      deHum: true,
      highPassFreq: 75,
      deHarsh: true,
      deHarshAmount: 65,
      lowPassFreq: 17500,
    },
    bass: {
      enabled: true,
      subBoostDb: 1.5,
      subFreq: 120,
      punchDb: 1.5,
      subHarmonics: 0,
      monoBelowFreq: 160,
    },
    clarity: {
      enabled: true,
      airDb: 3.5,
      presenceDb: 5.0,
      vocalShine: 80,
    },
    sonicHd: {
      enabled: true,
      mode: 'solid-state',
      drive: 25,
      warmth: 35,
      analogGlue: 65,
    },
    spatial: {
      enabled: true,
      stereoWidth: 80, // focused center mono vocal
      mode: 'mid-side',
      surroundSpread: 10,
    },
    loudness: {
      ceilingDb: -1.0,
      inputGainDb: 3.0,
      limiterRelease: 70,
    },
  },
  custom: {
    id: 'custom-master',
    name: 'Custom Manual Settings',
    genre: 'custom',
    description: 'Full manual studio control across every individual DSP stage and streaming loudness normalization target.',
    cleanup: {
      enabled: true,
      deHum: true,
      highPassFreq: 30,
      deHarsh: true,
      deHarshAmount: 30,
      lowPassFreq: 20500,
    },
    bass: {
      enabled: true,
      subBoostDb: 3.0,
      subFreq: 55,
      punchDb: 2.5,
      subHarmonics: 25,
      monoBelowFreq: 100,
    },
    clarity: {
      enabled: true,
      airDb: 3.5,
      presenceDb: 2.5,
      vocalShine: 50,
    },
    sonicHd: {
      enabled: true,
      mode: 'tape',
      drive: 35,
      warmth: 40,
      analogGlue: 45,
    },
    spatial: {
      enabled: true,
      stereoWidth: 120,
      mode: 'synthetic-room',
      surroundSpread: 45,
    },
    loudness: {
      ceilingDb: -1.0,
      inputGainDb: 2.5,
      limiterRelease: 80,
    },
  },
};
