import React, { useState } from 'react';
import {
  X,
  FileText,
  Download,
  CheckCircle2,
  XCircle,
  Copy,
  Calendar,
  Users,
  Vote,
  Layers,
} from 'lucide-react';
import type { MeetingRoomState, Motion, Topic, Attendee } from '../types';

interface MeetingMinutesModalProps {
  isOpen: boolean;
  onClose: () => void;
  roomState: MeetingRoomState;
}

export function MeetingMinutesModal({
  isOpen,
  onClose,
  roomState,
}: MeetingMinutesModalProps) {
  const [copied, setCopied] = useState(false);
  const [exportFormat, setExportFormat] = useState<'markdown' | 'text' | 'csv'>('markdown');

  if (!isOpen) return null;

  const { roomTitle, roomId, startedAt, topics, motionHistory, activeMotion, attendees, meetingStatus } = roomState;
  const dateStr = new Date(startedAt).toLocaleString();
  const attendeeList = Object.values(attendees);

  const generateMarkdown = () => {
    let md = `# Official Meeting Minutes: ${roomTitle}\n`;
    md += `**Room Identifier:** \`#${roomId}\`  \n`;
    md += `**Convened Date:** ${dateStr}  \n`;
    md += `**Session Status:** ${meetingStatus.toUpperCase()}  \n`;
    md += `**Quorum Attendance:** ${attendeeList.length} Connected Participants  \n\n`;

    md += `## 1. Attendance Roster\n`;
    attendeeList.forEach((att, i) => {
      md += `${i + 1}. **${att.name}** (${att.role.toUpperCase()}) - ${att.status}\n`;
    });
    md += `\n`;

    md += `## 2. Agenda & Topics Deliberated\n`;
    if (topics.length === 0) {
      md += `*No specific topics scheduled.*\n\n`;
    } else {
      topics.forEach((t, i) => {
        md += `### ${i + 1}. ${t.title} [Status: ${t.status.toUpperCase()}]\n`;
        if (t.presenter) md += `- **Presenter:** ${t.presenter}\n`;
        if (t.description) md += `- **Summary:** ${t.description}\n`;
        if (t.tags && t.tags.length > 0) md += `- **Tags:** ${t.tags.join(', ')}\n`;
        md += `\n`;
      });
    }

    md += `## 3. Voting Resolutions & Motions\n`;
    const allMotions = [...(activeMotion ? [activeMotion] : []), ...motionHistory];
    if (allMotions.length === 0) {
      md += `*No motions or ballots recorded.*\n\n`;
    } else {
      allMotions.forEach((m, i) => {
        md += `### Motion ${i + 1}: ${m.title}\n`;
        md += `- **Proposed By:** ${m.proposedBy}\n`;
        md += `- **Result:** ${m.status.toUpperCase()} (${m.tally.ya} YA, ${m.tally.na} NA, ${m.tally.abstain} ABSTAIN)\n`;
        if (m.description) md += `- **Description:** ${m.description}\n`;
        if (m.resultSummary) md += `- **Summary:** ${m.resultSummary}\n`;
        md += `\n`;
      });
    }

    md += `---\n*Generated by 2026 indiebrotherhood Meeting System*\n`;
    return md;
  };

  const generateCSV = () => {
    let csv = `"Section","Item","Detail 1","Detail 2","Detail 3"\n`;
    csv += `"Header","Meeting Title","${roomTitle}","Room ID","${roomId}"\n`;
    csv += `"Header","Convened","${dateStr}","Status","${meetingStatus}"\n`;

    topics.forEach((t, i) => {
      csv += `"Agenda Topic","${i + 1}. ${t.title.replace(/"/g, '""')}","Presenter: ${t.presenter || ''}","Status: ${t.status}","${(t.description || '').replace(/"/g, '""')}"\n`;
    });

    const allMotions = [...(activeMotion ? [activeMotion] : []), ...motionHistory];
    allMotions.forEach((m, i) => {
      csv += `"Voting Motion","${i + 1}. ${m.title.replace(/"/g, '""')}","Result: ${m.status}","Tally: ${m.tally.ya} Ya / ${m.tally.na} Na / ${m.tally.abstain} Abstain","Proposed by: ${m.proposedBy}"\n`;
    });

    attendeeList.forEach((att) => {
      csv += `"Attendance","${att.name.replace(/"/g, '""')}","Role: ${att.role}","Status: ${att.status}",""\n`;
    });

    return csv;
  };

  const handleDownload = () => {
    let content = '';
    let mimeType = 'text/plain';
    let extension = 'txt';

    if (exportFormat === 'markdown') {
      content = generateMarkdown();
      mimeType = 'text/markdown';
      extension = 'md';
    } else if (exportFormat === 'csv') {
      content = generateCSV();
      mimeType = 'text/csv';
      extension = 'csv';
    } else {
      content = generateMarkdown();
      mimeType = 'text/plain';
      extension = 'txt';
    }

    const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `meeting-minutes-${roomId}-${new Date().toISOString().slice(0, 10)}.${extension}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    const text = generateMarkdown();
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div id="minutes-modal-overlay" className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 overflow-y-auto">
      <div id="minutes-modal-content" className="bg-white rounded-2xl shadow-2xl max-w-3xl w-full border border-slate-200 overflow-hidden my-6">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 bg-slate-900 text-white">
          <div className="flex items-center gap-2.5">
            <div className="p-1.5 bg-blue-600 rounded-lg">
              <FileText className="w-5 h-5 text-white" />
            </div>
            <div>
              <h2 className="text-base font-semibold text-white">Official Meeting Minutes & Record</h2>
              <p className="text-xs text-slate-400">Formal summary of agenda topics, vote tallies, and attendance</p>
            </div>
          </div>
          <button
            id="close-minutes-modal-btn"
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Preview & Export Controls */}
        <div className="p-6 space-y-5 max-h-[70vh] overflow-y-auto">
          {/* Format Selector Bar */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-slate-50 p-3 rounded-xl border border-slate-200">
            <div className="flex items-center gap-2">
              <span className="text-xs font-semibold text-slate-700">Export Format:</span>
              <div className="flex gap-1">
                {(['markdown', 'text', 'csv'] as const).map((fmt) => (
                  <button
                    key={fmt}
                    type="button"
                    onClick={() => setExportFormat(fmt)}
                    className={`px-2.5 py-1 rounded-lg text-xs font-semibold uppercase transition-colors ${
                      exportFormat === fmt
                        ? 'bg-blue-600 text-white shadow-xs'
                        : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-100'
                    }`}
                  >
                    .{fmt}
                  </button>
                ))}
              </div>
            </div>

            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={handleCopy}
                className="px-3 py-1.5 bg-white border border-slate-200 hover:bg-slate-100 text-slate-700 text-xs font-semibold rounded-lg shadow-xs flex items-center gap-1.5 transition-colors"
              >
                <Copy className="w-3.5 h-3.5" />
                <span>{copied ? 'Copied to Clipboard!' : 'Copy Text'}</span>
              </button>
              <button
                id="download-minutes-btn"
                type="button"
                onClick={handleDownload}
                className="px-4 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold rounded-lg shadow-xs flex items-center gap-1.5 transition-colors"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download Minutes</span>
              </button>
            </div>
          </div>

          {/* Rendered Preview Box */}
          <div className="bg-slate-900 text-slate-100 p-4 rounded-xl font-mono text-xs overflow-x-auto whitespace-pre-wrap leading-relaxed max-h-[350px] border border-slate-800">
            {exportFormat === 'csv' ? generateCSV() : generateMarkdown()}
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-slate-100 bg-slate-50 flex justify-between items-center text-xs text-slate-500">
          <span>2026 indiebrotherhood Records</span>
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-200 hover:bg-slate-300 text-slate-800 font-medium rounded-xl transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
