import React, { useState } from 'react';
import { Scale, ShieldCheck, AlertCircle, X } from 'lucide-react';

interface TosModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAccept: () => void;
  tosAccepted: boolean;
}

export const TosModal: React.FC<TosModalProps> = ({
  isOpen,
  onClose,
  onAccept,
  tosAccepted
}) => {
  const [agreed, setAgreed] = useState(tosAccepted);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/85 backdrop-blur-md z-50 flex items-center justify-center p-4">
      <div className="bg-zinc-950 border border-zinc-800 max-w-2xl w-full rounded-2xl p-6 shadow-2xl flex flex-col justify-between max-h-[90vh]">
        
        {/* MODAL HEADER */}
        <div>
          <div className="flex items-center justify-between border-b border-zinc-800 pb-4 mb-4">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-center text-amber-400">
                <Scale className="w-5 h-5" />
              </div>
              <div>
                <h2 className="text-base font-bold text-white flex items-center gap-2">
                  Terms of Service & Legal Immunity Waiver
                </h2>
                <p className="text-xs text-zinc-400">
                  IndieBrotherhood Official Legal Framework
                </p>
              </div>
            </div>

            {tosAccepted && (
              <button 
                onClick={onClose}
                className="p-1.5 rounded-lg bg-zinc-900 text-zinc-400 hover:text-white transition"
              >
                <X className="w-5 h-5" />
              </button>
            )}
          </div>

          {/* LEGAL CLAUSES BODY */}
          <div className="space-y-3.5 text-xs text-zinc-300 leading-relaxed overflow-y-auto max-h-[50vh] pr-2 custom-scrollbar">
            
            <div className="p-3 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-200 font-semibold flex items-start gap-2">
              <AlertCircle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
              <span>
                PLEASE READ THIS BINDING LEGAL AGREEMENT CAREFULLY BEFORE USING LYRIC PRO STUDIO.
              </span>
            </div>

            <div className="space-y-2 text-zinc-300">
              <p>
                <strong className="text-amber-400">1. Absolute Waiver of Legal Action & Court Rights:</strong>
                {" "}By checking the agreement box and accepting these terms, you explicitly, irrevocably, and fully agree that you will NOT be able to take <strong>indiebrother</strong>, the <strong>indiebrotherhood</strong>, or any of the owners of the <strong>indiebrotherhood</strong> to court under any circumstances. You covenant and agree never to initiate, maintain, or participate in any lawsuit, class action, civil action, or legal proceeding in any court or jurisdiction against the owners or creators.
              </p>

              <p>
                <strong className="text-amber-400">2. Complete Immunity & Zero Liability:</strong>
                {" "}You agree that you will not put any blame, liability, or legal fault upon the owners or developers of the <strong>indiebrotherhood</strong> for any lyrics, text, rhymes, concepts, or explicit content generated by this application. You agree this waiver is bulletproof and designed to completely shield the owners from any legal claims, damages, copyright issues, or losses.
              </p>

              <p>
                <strong className="text-amber-400">3. Explicit Content Sole Responsibility:</strong>
                {" "}If you choose to activate Explicit Content Mode, you acknowledge that you are 100% solely responsible for all curse words, explicit language, or adult themes generated or distributed by you. The <strong>indiebrother</strong> and <strong>indiebrotherhood</strong> assume zero responsibility or liability for any content produced with or without explicit mode enabled.
              </p>

              <p>
                <strong className="text-amber-400">4. User Content Usage:</strong>
                {" "}All lyrics generated through Lyric Pro Studio are granted for creative and commercial songwriting use, provided that the user maintains full compliance with this legal agreement and waiver.
              </p>
            </div>

          </div>
        </div>

        {/* MODAL FOOTER & ACCEPTANCE */}
        <div className="border-t border-zinc-800 pt-4 mt-4 space-y-4">
          <label className="flex items-start space-x-3 cursor-pointer p-3 rounded-xl bg-zinc-900/80 border border-zinc-800 hover:border-zinc-700 transition">
            <input
              type="checkbox"
              checked={agreed}
              onChange={(e) => setAgreed(e.target.checked)}
              className="mt-0.5 accent-amber-400 w-4 h-4 rounded cursor-pointer"
            />
            <span className="text-xs text-zinc-200 font-medium leading-snug">
              I have read, understood, and irrevocably accept the Terms of Service. By accepting terms, I agree that I cannot take <strong className="text-amber-400">indiebrother</strong> or the owners of <strong className="text-amber-400">indiebrotherhood</strong> to court nor place any blame upon them for any content produced.
            </span>
          </label>

          <div className="flex items-center space-x-3">
            <button
              type="button"
              disabled={!agreed}
              onClick={() => {
                if (agreed) {
                  onAccept();
                  onClose();
                }
              }}
              className={`w-full py-3 rounded-xl font-bold text-xs flex items-center justify-center gap-2 transition shadow-lg ${
                agreed
                  ? 'bg-amber-400 hover:bg-amber-300 text-zinc-950 shadow-amber-400/20'
                  : 'bg-zinc-800 text-zinc-500 cursor-not-allowed'
              }`}
            >
              <ShieldCheck className="w-4 h-4" />
              <span>ACCEPT TERMS & CONTINUE TO STUDIO</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
